Compiling source
	intg_tests/dataproviders:0.0.0
WARNING [tests/new-data-provider-tests.bal:(121:9,121:21)] unused variable 'a'
WARNING [tests/new-data-provider-tests.bal:(153:9,153:21)] unused variable 'a'

Running Tests with Coverage

	dataproviders

	testGetState:1 has failed.

		[pass] testGetState#0

		[fail] testGetState#1:

		    error {ballerina/test:0}TestError ("Assertion Failed!
			 
			expected: '20'
			actual	: '200'")
				callableName: createBallerinaError moduleName: ballerina.test.0 fileName: assert.bal lineNumber: 41
				callableName: assertEquals moduleName: ballerina.test.0 fileName: assert.bal lineNumber: 109
				callableName: testGetState moduleName: intg_tests.dataproviders$test.0.tests.new-data-provider-tests fileName: tests/new-data-provider-tests.bal lineNumber: 344
				callableName: testGetState$lambda19$ moduleName: intg_tests.dataproviders$test.0.tests.test_execute-generated_*****lineNumber: 23
				callableName: call moduleName: ballerina.lang.function.0 fileName: function.bal lineNumber: 37
				callableName: executeTestFunction moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 129
				callableName: executeDataDrivenTest moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 114
				callableName: prepareDataDrivenTest moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 105
				callableName: executeDataDrivenTestSet moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 63
				callableName: executeTest moduleName: ballerina.test.0 fileName: serialExecuter.bal lineNumber: 28
				callableName: executeTests moduleName: ballerina.test.0 fileName: execute.bal lineNumber: 81
				callableName: startSuite moduleName: ballerina.test.0 fileName: execute.bal lineNumber: 53
				callableName: __execute__ moduleName: intg_tests.dataproviders$test.0.tests.test_execute-generated_*****lineNumber: 27
			


		1 passing
		1 failing
		0 skipped

		Test execution time :*****s

	dataproviders.module1


		No tests found

		Test execution time :*****s

Generating Test Report
	data-providers/target/report/test_results.json

error: there are test failures